#!/usr/bin/env bash
# Per-client gate for the qBittorrent magnet scenario: feed a magnet URI
# to the webUI's `/api/v2/torrents/add` endpoint via `urls=`, poll for
# completion, SHA-256 the downloaded file against fixture.bin.
#
# This drives the BEP 9 ut_metadata exchange end-to-end: qBittorrent
# starts with no metadata, dials magpie, performs the BEP 10 extension
# handshake, requests metadata pieces, verifies the SHA-1, then begins
# the data download. PASS ⇒ magpie's metadata-server path is interop-clean.
#
# Exit: 0 on SHA-256 match within deadline, non-zero otherwise.
set -euo pipefail

COMPOSE_FILE="$1"
DEADLINE_SECS="${INTEROP_DEADLINE_SECS:-180}"
WEB_HOST="${QBT_WEB_HOST:-http://127.0.0.1:8080}"
USER="${QBT_USER:-admin}"
PASS="${QBT_PASS:-adminadmin}"

need() { command -v "$1" >/dev/null || { echo "$1 required" >&2; exit 2; }; }
need curl
need jq
need sha256sum

login() {
  curl -sS --fail -c /tmp/qbt.cookies \
    -H "Referer: $WEB_HOST" \
    --data-urlencode "username=$USER" --data-urlencode "password=$PASS" \
    "$WEB_HOST/api/v2/auth/login"
}
for _ in $(seq 1 90); do
  if login 2>/dev/null | grep -q Ok; then break; fi
  sleep 1
done
login | grep -q Ok || { echo "qBittorrent webUI login failed after 90s" >&2; exit 1; }

# Read the magnet URI generated by `generate_fixture` out of the shared
# volume, plus the expected data so we can SHA-256 at the end.
docker compose -f "$COMPOSE_FILE" cp leech:/shared/fixture.magnet /tmp/fixture.magnet
docker compose -f "$COMPOSE_FILE" cp leech:/shared/fixture.bin /tmp/expected.bin
MAGNET_URI=$(cat /tmp/fixture.magnet)
echo "[qbt-magnet] magnet=${MAGNET_URI}"

# Add via magnet URI. qBittorrent webUI accepts urls= (newline-separated
# list of magnet URIs / .torrent URLs).
curl -sS --fail -b /tmp/qbt.cookies \
  -H "Referer: $WEB_HOST" \
  --data-urlencode "urls=${MAGNET_URI}" \
  --data-urlencode "savepath=/downloads" \
  "$WEB_HOST/api/v2/torrents/add"

# Poll until the leech finishes. State progression:
#
#   metaDL       -- waiting for metadata via ut_metadata (BEP 9)
#   downloading  -- has metadata, downloading pieces from magpie
#   uploading|stalledUP|completed -- done
#
deadline=$(( $(date +%s) + DEADLINE_SECS ))
while [ "$(date +%s)" -lt "$deadline" ]; do
  state=$(curl -sS -b /tmp/qbt.cookies -H "Referer: $WEB_HOST" "$WEB_HOST/api/v2/torrents/info" \
          | jq -r '.[0].state // "unknown"')
  progress=$(curl -sS -b /tmp/qbt.cookies -H "Referer: $WEB_HOST" "$WEB_HOST/api/v2/torrents/info" \
          | jq -r '.[0].progress // 0')
  echo "[qbt-magnet] state=$state progress=$progress"
  case "$state" in
    uploading|stalledUP|pausedUP|checkingUP|completed) break ;;
    error|missingFiles) echo "fatal state: $state" >&2; exit 1 ;;
  esac
  sleep 2
done
[ "$(date +%s)" -lt "$deadline" ] || { echo "deadline exceeded" >&2; exit 1; }

docker compose -f "$COMPOSE_FILE" cp leech:/downloads/interop.bin /tmp/got.bin
expected_sha=$(sha256sum /tmp/expected.bin | awk '{print $1}')
got_sha=$(sha256sum /tmp/got.bin | awk '{print $1}')
echo "[qbt-magnet] expected_sha=$expected_sha got_sha=$got_sha"
[ "$expected_sha" = "$got_sha" ] || {
  echo "SHA-256 mismatch" >&2
  exit 1
}
echo "[qbt-magnet] PASS"
